//! The C standard library (`libc`, the ISO C headers) and the POSIX system
//! interface (`posix`). C++ and Objective-C share these tables: a C header
//! included from either still declares the same functions.

/// Headers of ISO C (`<stdio.h>`), whose functions belong to `libc`.
const LIBC_HEADERS: &[&str] = &[
    "assert.h",
    "complex.h",
    "ctype.h",
    "errno.h",
    "fenv.h",
    "float.h",
    "inttypes.h",
    "iso646.h",
    "limits.h",
    "locale.h",
    "math.h",
    "setjmp.h",
    "signal.h",
    "stdalign.h",
    "stdarg.h",
    "stdatomic.h",
    "stdbit.h",
    "stdbool.h",
    "stdckdint.h",
    "stddef.h",
    "stdint.h",
    "stdio.h",
    "stdlib.h",
    "stdnoreturn.h",
    "string.h",
    "tgmath.h",
    "threads.h",
    "time.h",
    "uchar.h",
    "wchar.h",
    "wctype.h",
];

/// Headers POSIX adds on top of ISO C (`<unistd.h>`), plus the `sys/`,
/// `netinet/`, `arpa/` and `net/` families matched by [`is_posix_header`].
const POSIX_HEADERS: &[&str] = &[
    "aio.h",
    "cpio.h",
    "dirent.h",
    "dlfcn.h",
    "fcntl.h",
    "fnmatch.h",
    "ftw.h",
    "glob.h",
    "grp.h",
    "iconv.h",
    "langinfo.h",
    "libgen.h",
    "monetary.h",
    "mqueue.h",
    "netdb.h",
    "nl_types.h",
    "poll.h",
    "pthread.h",
    "pwd.h",
    "regex.h",
    "sched.h",
    "search.h",
    "semaphore.h",
    "spawn.h",
    "strings.h",
    "syslog.h",
    "tar.h",
    "termios.h",
    "ulimit.h",
    "unistd.h",
    "utime.h",
    "utmpx.h",
    "wordexp.h",
];

/// Directories of POSIX headers (`<sys/socket.h>`, `<netinet/in.h>`).
const POSIX_HEADER_DIRS: &[&str] = &["sys/", "netinet/", "arpa/", "net/"];

/// The standard-library package an angle-bracket include names (`libc` for
/// `<stdio.h>`, `posix` for `<unistd.h>` or `<sys/socket.h>`). A quoted
/// include is the repository's and never reaches this.
pub(crate) fn c_header_package(header: &str) -> Option<&'static str> {
    if LIBC_HEADERS.contains(&header) {
        Some("libc")
    } else if is_posix_header(header) {
        Some("posix")
    } else {
        None
    }
}

fn is_posix_header(header: &str) -> bool {
    POSIX_HEADERS.contains(&header)
        || POSIX_HEADER_DIRS.iter().any(|dir| {
            header
                .strip_prefix(dir)
                .is_some_and(|rest| rest.ends_with(".h"))
        })
}

/// Common functions of libc and POSIX with the header that declares them,
/// so a call is certain when that header is included (`malloc` after
/// `#include <stdlib.h>`) and only likely when the name alone matches.
const C_FUNCTIONS: &[(&str, &str)] = &[
    // <stdio.h>
    ("printf", "stdio.h"),
    ("fprintf", "stdio.h"),
    ("sprintf", "stdio.h"),
    ("snprintf", "stdio.h"),
    ("vprintf", "stdio.h"),
    ("vfprintf", "stdio.h"),
    ("vsprintf", "stdio.h"),
    ("vsnprintf", "stdio.h"),
    ("scanf", "stdio.h"),
    ("fscanf", "stdio.h"),
    ("sscanf", "stdio.h"),
    ("puts", "stdio.h"),
    ("fputs", "stdio.h"),
    ("putchar", "stdio.h"),
    ("fputc", "stdio.h"),
    ("putc", "stdio.h"),
    ("getchar", "stdio.h"),
    ("fgetc", "stdio.h"),
    ("getc", "stdio.h"),
    ("fgets", "stdio.h"),
    ("ungetc", "stdio.h"),
    ("fopen", "stdio.h"),
    ("freopen", "stdio.h"),
    ("fclose", "stdio.h"),
    ("fflush", "stdio.h"),
    ("fread", "stdio.h"),
    ("fwrite", "stdio.h"),
    ("fseek", "stdio.h"),
    ("ftell", "stdio.h"),
    ("rewind", "stdio.h"),
    ("feof", "stdio.h"),
    ("ferror", "stdio.h"),
    ("clearerr", "stdio.h"),
    ("perror", "stdio.h"),
    ("remove", "stdio.h"),
    ("rename", "stdio.h"),
    ("tmpfile", "stdio.h"),
    ("setvbuf", "stdio.h"),
    ("fileno", "stdio.h"),
    ("fdopen", "stdio.h"),
    ("popen", "stdio.h"),
    ("pclose", "stdio.h"),
    ("getline", "stdio.h"),
    // <stdlib.h>
    ("malloc", "stdlib.h"),
    ("calloc", "stdlib.h"),
    ("realloc", "stdlib.h"),
    ("free", "stdlib.h"),
    ("aligned_alloc", "stdlib.h"),
    ("exit", "stdlib.h"),
    ("_Exit", "stdlib.h"),
    ("abort", "stdlib.h"),
    ("atexit", "stdlib.h"),
    ("getenv", "stdlib.h"),
    ("setenv", "stdlib.h"),
    ("unsetenv", "stdlib.h"),
    ("system", "stdlib.h"),
    ("qsort", "stdlib.h"),
    ("bsearch", "stdlib.h"),
    ("atoi", "stdlib.h"),
    ("atol", "stdlib.h"),
    ("atoll", "stdlib.h"),
    ("atof", "stdlib.h"),
    ("strtol", "stdlib.h"),
    ("strtoll", "stdlib.h"),
    ("strtoul", "stdlib.h"),
    ("strtoull", "stdlib.h"),
    ("strtod", "stdlib.h"),
    ("strtof", "stdlib.h"),
    ("abs", "stdlib.h"),
    ("labs", "stdlib.h"),
    ("div", "stdlib.h"),
    ("rand", "stdlib.h"),
    ("srand", "stdlib.h"),
    ("mkstemp", "stdlib.h"),
    ("realpath", "stdlib.h"),
    // <string.h>
    ("memcpy", "string.h"),
    ("memmove", "string.h"),
    ("memset", "string.h"),
    ("memcmp", "string.h"),
    ("memchr", "string.h"),
    ("strlen", "string.h"),
    ("strnlen", "string.h"),
    ("strcpy", "string.h"),
    ("strncpy", "string.h"),
    ("strcat", "string.h"),
    ("strncat", "string.h"),
    ("strcmp", "string.h"),
    ("strncmp", "string.h"),
    ("strcoll", "string.h"),
    ("strchr", "string.h"),
    ("strrchr", "string.h"),
    ("strstr", "string.h"),
    ("strtok", "string.h"),
    ("strtok_r", "string.h"),
    ("strspn", "string.h"),
    ("strcspn", "string.h"),
    ("strpbrk", "string.h"),
    ("strdup", "string.h"),
    ("strndup", "string.h"),
    ("strerror", "string.h"),
    ("strcasecmp", "strings.h"),
    ("strncasecmp", "strings.h"),
    // <ctype.h>
    ("isalpha", "ctype.h"),
    ("isdigit", "ctype.h"),
    ("isalnum", "ctype.h"),
    ("isspace", "ctype.h"),
    ("isupper", "ctype.h"),
    ("islower", "ctype.h"),
    ("isxdigit", "ctype.h"),
    ("ispunct", "ctype.h"),
    ("isprint", "ctype.h"),
    ("toupper", "ctype.h"),
    ("tolower", "ctype.h"),
    // <math.h>
    ("sqrt", "math.h"),
    ("pow", "math.h"),
    ("exp", "math.h"),
    ("log", "math.h"),
    ("log2", "math.h"),
    ("log10", "math.h"),
    ("sin", "math.h"),
    ("cos", "math.h"),
    ("tan", "math.h"),
    ("atan", "math.h"),
    ("atan2", "math.h"),
    ("floor", "math.h"),
    ("ceil", "math.h"),
    ("round", "math.h"),
    ("trunc", "math.h"),
    ("fabs", "math.h"),
    ("fmod", "math.h"),
    ("fmin", "math.h"),
    ("fmax", "math.h"),
    ("hypot", "math.h"),
    // <time.h>
    ("time", "time.h"),
    ("clock", "time.h"),
    ("difftime", "time.h"),
    ("mktime", "time.h"),
    ("localtime", "time.h"),
    ("localtime_r", "time.h"),
    ("gmtime", "time.h"),
    ("gmtime_r", "time.h"),
    ("strftime", "time.h"),
    ("clock_gettime", "time.h"),
    ("nanosleep", "time.h"),
    // <signal.h>, <setjmp.h>, <assert.h>, <locale.h>, <wchar.h>
    ("signal", "signal.h"),
    ("raise", "signal.h"),
    ("kill", "signal.h"),
    ("sigaction", "signal.h"),
    ("sigemptyset", "signal.h"),
    ("sigaddset", "signal.h"),
    ("setjmp", "setjmp.h"),
    ("longjmp", "setjmp.h"),
    ("assert", "assert.h"),
    ("setlocale", "locale.h"),
    ("wcslen", "wchar.h"),
    ("wprintf", "wchar.h"),
    // <threads.h>
    ("thrd_create", "threads.h"),
    ("thrd_join", "threads.h"),
    ("mtx_init", "threads.h"),
    ("mtx_lock", "threads.h"),
    ("mtx_unlock", "threads.h"),
    // <unistd.h>
    ("read", "unistd.h"),
    ("write", "unistd.h"),
    ("close", "unistd.h"),
    ("lseek", "unistd.h"),
    ("fork", "unistd.h"),
    ("execv", "unistd.h"),
    ("execve", "unistd.h"),
    ("execvp", "unistd.h"),
    ("execl", "unistd.h"),
    ("execlp", "unistd.h"),
    ("_exit", "unistd.h"),
    ("pipe", "unistd.h"),
    ("dup", "unistd.h"),
    ("dup2", "unistd.h"),
    ("getpid", "unistd.h"),
    ("getppid", "unistd.h"),
    ("getuid", "unistd.h"),
    ("geteuid", "unistd.h"),
    ("getcwd", "unistd.h"),
    ("chdir", "unistd.h"),
    ("rmdir", "unistd.h"),
    ("unlink", "unistd.h"),
    ("access", "unistd.h"),
    ("sleep", "unistd.h"),
    ("usleep", "unistd.h"),
    ("isatty", "unistd.h"),
    ("sysconf", "unistd.h"),
    ("readlink", "unistd.h"),
    ("symlink", "unistd.h"),
    ("fsync", "unistd.h"),
    ("ftruncate", "unistd.h"),
    ("getopt", "unistd.h"),
    // <fcntl.h>, <sys/stat.h>, <sys/wait.h>, <sys/mman.h>
    ("open", "fcntl.h"),
    ("openat", "fcntl.h"),
    ("fcntl", "fcntl.h"),
    ("stat", "sys/stat.h"),
    ("fstat", "sys/stat.h"),
    ("lstat", "sys/stat.h"),
    ("mkdir", "sys/stat.h"),
    ("chmod", "sys/stat.h"),
    ("umask", "sys/stat.h"),
    ("wait", "sys/wait.h"),
    ("waitpid", "sys/wait.h"),
    ("mmap", "sys/mman.h"),
    ("munmap", "sys/mman.h"),
    ("mprotect", "sys/mman.h"),
    ("ioctl", "sys/ioctl.h"),
    ("select", "sys/select.h"),
    ("gettimeofday", "sys/time.h"),
    // <sys/socket.h>, <netdb.h>, <arpa/inet.h>, <poll.h>
    ("socket", "sys/socket.h"),
    ("bind", "sys/socket.h"),
    ("listen", "sys/socket.h"),
    ("accept", "sys/socket.h"),
    ("connect", "sys/socket.h"),
    ("send", "sys/socket.h"),
    ("sendto", "sys/socket.h"),
    ("recv", "sys/socket.h"),
    ("recvfrom", "sys/socket.h"),
    ("setsockopt", "sys/socket.h"),
    ("getsockopt", "sys/socket.h"),
    ("shutdown", "sys/socket.h"),
    ("getaddrinfo", "netdb.h"),
    ("freeaddrinfo", "netdb.h"),
    ("gethostbyname", "netdb.h"),
    ("inet_pton", "arpa/inet.h"),
    ("inet_ntop", "arpa/inet.h"),
    ("inet_addr", "arpa/inet.h"),
    ("htons", "arpa/inet.h"),
    ("htonl", "arpa/inet.h"),
    ("ntohs", "arpa/inet.h"),
    ("ntohl", "arpa/inet.h"),
    ("poll", "poll.h"),
    // <pthread.h>, <semaphore.h>, <sched.h>
    ("pthread_create", "pthread.h"),
    ("pthread_join", "pthread.h"),
    ("pthread_detach", "pthread.h"),
    ("pthread_self", "pthread.h"),
    ("pthread_exit", "pthread.h"),
    ("pthread_mutex_init", "pthread.h"),
    ("pthread_mutex_destroy", "pthread.h"),
    ("pthread_mutex_lock", "pthread.h"),
    ("pthread_mutex_trylock", "pthread.h"),
    ("pthread_mutex_unlock", "pthread.h"),
    ("pthread_cond_init", "pthread.h"),
    ("pthread_cond_wait", "pthread.h"),
    ("pthread_cond_timedwait", "pthread.h"),
    ("pthread_cond_signal", "pthread.h"),
    ("pthread_cond_broadcast", "pthread.h"),
    ("pthread_once", "pthread.h"),
    ("pthread_key_create", "pthread.h"),
    ("pthread_getspecific", "pthread.h"),
    ("pthread_setspecific", "pthread.h"),
    ("sem_init", "semaphore.h"),
    ("sem_wait", "semaphore.h"),
    ("sem_post", "semaphore.h"),
    ("sched_yield", "sched.h"),
    // <dlfcn.h>, <dirent.h>, <syslog.h>, <spawn.h>
    ("dlopen", "dlfcn.h"),
    ("dlsym", "dlfcn.h"),
    ("dlclose", "dlfcn.h"),
    ("dlerror", "dlfcn.h"),
    ("opendir", "dirent.h"),
    ("readdir", "dirent.h"),
    ("closedir", "dirent.h"),
    ("openlog", "syslog.h"),
    ("syslog", "syslog.h"),
    ("closelog", "syslog.h"),
    ("posix_spawn", "spawn.h"),
    ("posix_spawnp", "spawn.h"),
];

/// The header declaring a libc / POSIX function `name` and the package it
/// belongs to (`("stdlib.h", "libc")` for `malloc`).
pub(crate) fn c_function_header(name: &str) -> Option<(&'static str, &'static str)> {
    C_FUNCTIONS
        .iter()
        .find(|(function, _)| *function == name)
        .and_then(|(_, header)| Some((*header, c_header_package(header)?)))
}

/// Whether including `included` declares what `header` declares: the header
/// itself, or its C++ spelling (`<cstdio>` for `stdio.h`).
pub(crate) fn c_header_satisfied_by(header: &str, included: &str) -> bool {
    included == header
        || header
            .strip_suffix(".h")
            .is_some_and(|stem| !stem.contains('/') && included.strip_prefix('c') == Some(stem))
}
