//! The C++ standard library (`std`). The C headers it inherits
//! (`<stdio.h>`, `<unistd.h>`) keep their `libc` / `posix` package; see
//! [`super::c`].

/// Headers of the C++ standard library (`<vector>`), including the `<cstdio>`
/// spellings of the C headers.
const CPP_STD_HEADERS: &[&str] = &[
    "algorithm",
    "any",
    "array",
    "atomic",
    "barrier",
    "bit",
    "bitset",
    "cassert",
    "cctype",
    "cerrno",
    "cfloat",
    "charconv",
    "chrono",
    "cinttypes",
    "climits",
    "clocale",
    "cmath",
    "codecvt",
    "compare",
    "complex",
    "concepts",
    "condition_variable",
    "coroutine",
    "csetjmp",
    "csignal",
    "cstdarg",
    "cstddef",
    "cstdint",
    "cstdio",
    "cstdlib",
    "cstring",
    "ctime",
    "cwchar",
    "cwctype",
    "deque",
    "exception",
    "execution",
    "expected",
    "filesystem",
    "format",
    "forward_list",
    "fstream",
    "functional",
    "future",
    "initializer_list",
    "iomanip",
    "ios",
    "iosfwd",
    "iostream",
    "istream",
    "iterator",
    "latch",
    "limits",
    "list",
    "locale",
    "map",
    "memory",
    "memory_resource",
    "mutex",
    "new",
    "numbers",
    "numeric",
    "optional",
    "ostream",
    "print",
    "queue",
    "random",
    "ranges",
    "ratio",
    "regex",
    "scoped_allocator",
    "semaphore",
    "set",
    "shared_mutex",
    "source_location",
    "span",
    "sstream",
    "stack",
    "stdexcept",
    "stop_token",
    "streambuf",
    "string",
    "string_view",
    "syncstream",
    "system_error",
    "thread",
    "tuple",
    "type_traits",
    "typeindex",
    "typeinfo",
    "unordered_map",
    "unordered_set",
    "utility",
    "valarray",
    "variant",
    "vector",
    "version",
];

pub(crate) fn is_cpp_std_header(header: &str) -> bool {
    CPP_STD_HEADERS.contains(&header)
}

/// Free functions of `std` an unqualified call can reach under
/// `using namespace std;` (`sort(v.begin(), v.end())`).
const CPP_STD_FUNCTIONS: &[&str] = &[
    "accumulate",
    "advance",
    "all_of",
    "any_of",
    "back_inserter",
    "begin",
    "binary_search",
    "copy",
    "copy_if",
    "count",
    "count_if",
    "distance",
    "end",
    "equal",
    "fill",
    "find",
    "find_if",
    "for_each",
    "forward",
    "get",
    "getline",
    "iota",
    "lower_bound",
    "make_optional",
    "make_pair",
    "make_shared",
    "make_tuple",
    "make_unique",
    "max",
    "max_element",
    "min",
    "min_element",
    "move",
    "next",
    "none_of",
    "prev",
    "remove",
    "remove_if",
    "replace",
    "reverse",
    "sort",
    "stable_sort",
    "stod",
    "stoi",
    "stol",
    "stoll",
    "swap",
    "tie",
    "to_string",
    "transform",
    "unique",
    "upper_bound",
    "visit",
];

pub(crate) fn is_cpp_std_function(name: &str) -> bool {
    CPP_STD_FUNCTIONS.contains(&name)
}

/// Class templates and classes of `std` a variable can be declared with,
/// written bare under `using namespace std;` (`vector<int> xs;`), and whose
/// temporaries are values of `std` (`std::string(s).size()`).
const CPP_STD_TYPES: &[&str] = &[
    "array",
    "atomic",
    "bitset",
    "deque",
    "fstream",
    "function",
    "ifstream",
    "list",
    "map",
    "multimap",
    "multiset",
    "mutex",
    "ofstream",
    "optional",
    "pair",
    "priority_queue",
    "queue",
    "set",
    "shared_ptr",
    "span",
    "stack",
    "string",
    "string_view",
    "stringstream",
    "istringstream",
    "ostringstream",
    "thread",
    "tuple",
    "unique_ptr",
    "unordered_map",
    "unordered_set",
    "variant",
    "vector",
    "weak_ptr",
    "wstring",
];

pub(crate) fn is_cpp_std_type(name: &str) -> bool {
    CPP_STD_TYPES.contains(&name)
}
