//! The Elixir standard library: the modules of Elixir itself (`Enum`,
//! `IO`, `GenServer`), the `Kernel` functions and macros in scope in every
//! module, and the Erlang/OTP modules called as atoms (`:lists`, `:ets`).

/// Top-level modules of Elixir, ExUnit, Logger, Mix, IEx and EEx. A module
/// nested in one (`IO.ANSI`, `ExUnit.Case`) is the standard library's too.
const ELIXIR_STDLIB_MODULES: &[&str] = &[
    "Access",
    "Agent",
    "Application",
    "Atom",
    "Base",
    "Behaviour",
    "Bitwise",
    "Calendar",
    "Code",
    "Collectable",
    "Config",
    "Date",
    "DateTime",
    "Dict",
    "DynamicSupervisor",
    "EEx",
    "Enum",
    "Enumerable",
    "ExUnit",
    "Exception",
    "File",
    "Float",
    "Function",
    "GenEvent",
    "GenServer",
    "HashDict",
    "HashSet",
    "IEx",
    "IO",
    "Inspect",
    "Integer",
    "JSON",
    "Kernel",
    "Keyword",
    "List",
    "Logger",
    "Macro",
    "Map",
    "MapSet",
    "Mix",
    "Module",
    "NaiveDateTime",
    "Node",
    "OptionParser",
    "PartitionSupervisor",
    "Path",
    "Port",
    "Process",
    "Protocol",
    "Range",
    "Record",
    "Regex",
    "Registry",
    "Set",
    "Stream",
    "String",
    "StringIO",
    "Supervisor",
    "System",
    "Task",
    "Time",
    "Tuple",
    "URI",
    "Version",
];

/// Modules of Erlang/OTP's `erts`, `kernel`, `stdlib`, `crypto`, `ssl`,
/// `inets`, `public_key`, `os_mon`, `mnesia` and friends, called as atoms.
const ERLANG_OTP_MODULES: &[&str] = &[
    "application",
    "array",
    "base64",
    "binary",
    "calendar",
    "code",
    "crypto",
    "dets",
    "dict",
    "digraph",
    "disk_log",
    "erl_eval",
    "erl_parse",
    "erl_scan",
    "erlang",
    "error_logger",
    "ets",
    "file",
    "filelib",
    "filename",
    "gb_sets",
    "gb_trees",
    "gen_event",
    "gen_server",
    "gen_statem",
    "gen_tcp",
    "gen_udp",
    "global",
    "httpc",
    "inet",
    "io",
    "io_lib",
    "json",
    "lists",
    "logger",
    "maps",
    "math",
    "mnesia",
    "net_adm",
    "net_kernel",
    "orddict",
    "ordsets",
    "os",
    "persistent_term",
    "proplists",
    "public_key",
    "queue",
    "rand",
    "re",
    "rpc",
    "sets",
    "ssl",
    "string",
    "supervisor",
    "sys",
    "timer",
    "unicode",
    "uri_string",
    "zlib",
];

/// Functions and macros of `Kernel`, imported into every module.
const ELIXIR_KERNEL_FUNCTIONS: &[&str] = &[
    "abs",
    "apply",
    "binary_part",
    "bit_size",
    "byte_size",
    "ceil",
    "dbg",
    "defdelegate",
    "defexception",
    "defguard",
    "defimpl",
    "defoverridable",
    "defprotocol",
    "defstruct",
    "destructure",
    "div",
    "elem",
    "exit",
    "floor",
    "function_exported?",
    "get_in",
    "hd",
    "if",
    "inspect",
    "is_atom",
    "is_binary",
    "is_bitstring",
    "is_boolean",
    "is_float",
    "is_function",
    "is_integer",
    "is_list",
    "is_map",
    "is_map_key",
    "is_nil",
    "is_number",
    "is_pid",
    "is_struct",
    "is_tuple",
    "length",
    "macro_exported?",
    "make_ref",
    "map_size",
    "max",
    "min",
    "node",
    "not",
    "pop_in",
    "put_elem",
    "put_in",
    "raise",
    "rem",
    "reraise",
    "round",
    "self",
    "send",
    "spawn",
    "spawn_link",
    "spawn_monitor",
    "struct",
    "tap",
    "then",
    "throw",
    "tl",
    "to_charlist",
    "to_string",
    "trunc",
    "tuple_size",
    "unless",
    "update_in",
];

/// Special forms (`Kernel.SpecialForms`): `case`, `cond`, `for`, `with`.
const ELIXIR_SPECIAL_FORMS: &[&str] = &[
    "case",
    "cond",
    "for",
    "quote",
    "receive",
    "super",
    "try",
    "unquote",
    "unquote_splicing",
    "with",
];

/// Whether `module` (`Enum`, `IO.ANSI`) is part of Elixir: its outermost
/// segment is a standard-library module.
pub(crate) fn is_elixir_stdlib_module(module: &str) -> bool {
    let root = module.split('.').next().unwrap_or(module);
    ELIXIR_STDLIB_MODULES.contains(&root)
}

/// Whether `:module` (written without its colon) is an Erlang/OTP module.
pub(crate) fn is_erlang_otp_module(module: &str) -> bool {
    ERLANG_OTP_MODULES.contains(&module)
}

/// The `Kernel` module that brings a bare name into every module:
/// `Kernel` (`is_nil`, `raise`) or `Kernel.SpecialForms` (`case`).
pub(crate) fn elixir_kernel_module(name: &str) -> Option<&'static str> {
    if ELIXIR_KERNEL_FUNCTIONS.contains(&name) {
        Some("Kernel")
    } else if ELIXIR_SPECIAL_FORMS.contains(&name) {
        Some("Kernel.SpecialForms")
    } else {
        None
    }
}
