//! The Julia standard library: `Base` and `Core`, always in scope, and the
//! stdlib modules shipped with Julia that a `using` loads.

/// Modules shipped with Julia: `using LinearAlgebra` and `Statistics.mean`
/// name the standard library, `using DataFrames` does not.
const JULIA_STDLIB_MODULES: &[&str] = &[
    "Base",
    "Base64",
    "CRC32c",
    "Core",
    "Dates",
    "DelimitedFiles",
    "Distributed",
    "Downloads",
    "FileWatching",
    "Future",
    "InteractiveUtils",
    "LazyArtifacts",
    "LibCURL",
    "LibGit2",
    "Libdl",
    "LinearAlgebra",
    "Logging",
    "Markdown",
    "Mmap",
    "NetworkOptions",
    "Pkg",
    "Printf",
    "Profile",
    "REPL",
    "Random",
    "SHA",
    "Serialization",
    "SharedArrays",
    "Sockets",
    "SparseArrays",
    "Statistics",
    "TOML",
    "Tar",
    "Test",
    "UUIDs",
    "Unicode",
];

/// Common names `Base` exports, in scope in every module (`println`,
/// `push!`, `@time`).
const JULIA_BASE_EXPORTS: &[&str] = &[
    "@assert",
    "@async",
    "@debug",
    "@elapsed",
    "@error",
    "@info",
    "@inbounds",
    "@inline",
    "@isdefined",
    "@show",
    "@simd",
    "@sync",
    "@task",
    "@time",
    "@view",
    "@views",
    "@warn",
    "Array",
    "Char",
    "Dict",
    "Float32",
    "Float64",
    "Int",
    "Int32",
    "Int64",
    "Matrix",
    "NamedTuple",
    "Pair",
    "Set",
    "String",
    "Symbol",
    "Tuple",
    "UInt8",
    "Vector",
    "abs",
    "all",
    "any",
    "append!",
    "argmax",
    "argmin",
    "cat",
    "ceil",
    "collect",
    "convert",
    "copy",
    "count",
    "deepcopy",
    "delete!",
    "div",
    "eachindex",
    "empty!",
    "endswith",
    "enumerate",
    "error",
    "eltype",
    "exp",
    "fill",
    "filter",
    "filter!",
    "findall",
    "findfirst",
    "first",
    "floor",
    "foreach",
    "get",
    "get!",
    "getindex",
    "hasfield",
    "haskey",
    "hcat",
    "identity",
    "in",
    "include",
    "insert!",
    "isa",
    "isempty",
    "isequal",
    "isnothing",
    "join",
    "keys",
    "last",
    "length",
    "log",
    "lowercase",
    "map",
    "map!",
    "mapreduce",
    "max",
    "maximum",
    "merge",
    "min",
    "minimum",
    "mod",
    "ndims",
    "occursin",
    "ones",
    "pairs",
    "parse",
    "pop!",
    "popfirst!",
    "print",
    "println",
    "push!",
    "pushfirst!",
    "rand",
    "randn",
    "range",
    "read",
    "readline",
    "readlines",
    "reduce",
    "repeat",
    "replace",
    "reshape",
    "reverse",
    "round",
    "setdiff",
    "setindex!",
    "show",
    "similar",
    "size",
    "sort",
    "sort!",
    "split",
    "sprint",
    "sqrt",
    "startswith",
    "string",
    "strip",
    "sum",
    "throw",
    "trunc",
    "tryparse",
    "typeof",
    "union",
    "unique",
    "uppercase",
    "values",
    "vcat",
    "write",
    "zeros",
    "zip",
];

/// Names a stdlib module exports, so a bare `norm(x)` after `using
/// LinearAlgebra` is that module's.
const JULIA_MODULE_EXPORTS: &[(&str, &[&str])] = &[
    (
        "LinearAlgebra",
        &[
            "I",
            "cholesky",
            "cross",
            "det",
            "diag",
            "diagm",
            "dot",
            "eigen",
            "eigvals",
            "inv",
            "lu",
            "mul!",
            "norm",
            "normalize",
            "qr",
            "rank",
            "svd",
            "tr",
            "transpose",
        ],
    ),
    (
        "Statistics",
        &["cor", "cov", "mean", "median", "quantile", "std", "var"],
    ),
    (
        "Random",
        &[
            "randperm",
            "seed!",
            "shuffle",
            "shuffle!",
            "MersenneTwister",
            "Xoshiro",
        ],
    ),
    ("Printf", &["@printf", "@sprintf"]),
    (
        "Dates",
        &[
            "Date",
            "DateTime",
            "Day",
            "Hour",
            "Minute",
            "Month",
            "Second",
            "Year",
            "now",
            "today",
            "year",
            "month",
            "day",
            "dayofweek",
        ],
    ),
    (
        "Test",
        &[
            "@test",
            "@test_broken",
            "@test_logs",
            "@test_skip",
            "@test_throws",
            "@test_warn",
            "@testset",
            "@inferred",
        ],
    ),
    (
        "Logging",
        &[
            "@logmsg",
            "ConsoleLogger",
            "global_logger",
            "with_logger",
            "SimpleLogger",
        ],
    ),
    (
        "Distributed",
        &[
            "@distributed",
            "@everywhere",
            "@spawnat",
            "addprocs",
            "myid",
            "nprocs",
            "nworkers",
            "pmap",
            "remotecall",
            "rmprocs",
            "workers",
        ],
    ),
    ("SparseArrays", &["nnz", "sparse", "spzeros", "sprand"]),
    ("DelimitedFiles", &["readdlm", "writedlm"]),
    ("Serialization", &["deserialize", "serialize"]),
    ("Sockets", &["accept", "connect", "listen", "getaddrinfo"]),
    ("UUIDs", &["uuid1", "uuid4"]),
    ("Base64", &["base64decode", "base64encode"]),
    ("SHA", &["sha1", "sha256", "sha512"]),
    (
        "InteractiveUtils",
        &["@code_warntype", "@which", "subtypes", "versioninfo"],
    ),
];

/// Whether `module` is shipped with Julia (`Base` and `Core` included).
pub(crate) fn is_julia_stdlib_module(module: &str) -> bool {
    JULIA_STDLIB_MODULES.contains(&module)
}

pub(crate) fn is_julia_base_export(name: &str) -> bool {
    JULIA_BASE_EXPORTS.contains(&name)
}

/// Whether the stdlib `module` exports `name`.
pub(crate) fn julia_module_exports(module: &str, name: &str) -> bool {
    JULIA_MODULE_EXPORTS
        .iter()
        .any(|(exporter, names)| *exporter == module && names.contains(&name))
}
