//! The Perl standard library: the builtin functions (`CORE`) and the core
//! modules shipped with perl.

/// Modules shipped with perl (`Module::CoreList`), the common ones: `use
/// POSIX` and `POSIX::floor` name the standard library, `use Moose` does not.
const PERL_CORE_MODULES: &[&str] = &[
    "AutoLoader",
    "B",
    "Benchmark",
    "Carp",
    "Class::Struct",
    "Compress::Zlib",
    "Config",
    "Cwd",
    "Data::Dumper",
    "DB_File",
    "Devel::Peek",
    "Digest::MD5",
    "Digest::SHA",
    "DynaLoader",
    "Encode",
    "English",
    "Env",
    "Errno",
    "Exporter",
    "Fcntl",
    "File::Basename",
    "File::Compare",
    "File::Copy",
    "File::Find",
    "File::Glob",
    "File::Path",
    "File::Spec",
    "File::Spec::Functions",
    "File::Temp",
    "File::stat",
    "FileHandle",
    "FindBin",
    "Getopt::Long",
    "Getopt::Std",
    "Hash::Util",
    "HTTP::Tiny",
    "I18N::Langinfo",
    "IO::Compress::Gzip",
    "IO::Dir",
    "IO::File",
    "IO::Handle",
    "IO::Pipe",
    "IO::Poll",
    "IO::Select",
    "IO::Socket",
    "IO::Socket::INET",
    "IO::Socket::IP",
    "IO::Uncompress::Gunzip",
    "IPC::Cmd",
    "IPC::Open2",
    "IPC::Open3",
    "JSON::PP",
    "List::Util",
    "Locale::Maketext",
    "MIME::Base64",
    "Math::BigFloat",
    "Math::BigInt",
    "Math::Complex",
    "Math::Trig",
    "Memoize",
    "Module::Load",
    "Opcode",
    "POSIX",
    "Pod::Usage",
    "Safe",
    "Scalar::Util",
    "SelectSaver",
    "Socket",
    "Storable",
    "Symbol",
    "Sys::Hostname",
    "Term::ANSIColor",
    "Term::ReadLine",
    "Test::Builder",
    "Test::Harness",
    "Test::More",
    "Test::Simple",
    "Text::Abbrev",
    "Text::Balanced",
    "Text::ParseWords",
    "Text::Tabs",
    "Text::Wrap",
    "Thread::Queue",
    "Tie::Hash",
    "Time::HiRes",
    "Time::Local",
    "Time::Piece",
    "Time::gmtime",
    "Time::localtime",
    "UNIVERSAL",
    "Unicode::Normalize",
    "XSLoader",
    "attributes",
    "autodie",
    "base",
    "bigint",
    "charnames",
    "constant",
    "fields",
    "if",
    "overload",
    "parent",
    "threads",
    "threads::shared",
];

/// What a core module exports by default, so a bare `Dumper($x)` after
/// `use Data::Dumper;` (no import list) is that module's.
const PERL_DEFAULT_EXPORTS: &[(&str, &[&str])] = &[
    ("Carp", &["carp", "cluck", "confess", "croak"]),
    ("Cwd", &["cwd", "getcwd", "fastcwd", "fastgetcwd"]),
    ("Data::Dumper", &["Dumper"]),
    (
        "Encode",
        &["decode", "decode_utf8", "encode", "encode_utf8"],
    ),
    ("File::Basename", &["basename", "dirname", "fileparse"]),
    ("File::Copy", &["copy", "move"]),
    ("File::Find", &["find", "finddepth"]),
    ("File::Path", &["mkpath", "rmtree"]),
    (
        "File::Spec::Functions",
        &[
            "canonpath",
            "catdir",
            "catfile",
            "curdir",
            "file_name_is_absolute",
            "no_upwards",
            "path",
            "rootdir",
            "updir",
        ],
    ),
    ("File::Temp", &["tempdir", "tempfile"]),
    ("Getopt::Long", &["GetOptions"]),
    ("JSON::PP", &["decode_json", "encode_json"]),
    ("MIME::Base64", &["decode_base64", "encode_base64"]),
    (
        "POSIX",
        &[
            "ceil",
            "floor",
            "fmod",
            "strftime",
            "strtol",
            "strtod",
            "setlocale",
            "isatty",
            "mktime",
            "_exit",
            "dup2",
            "pow",
            "setsid",
            "WNOHANG",
            "EXIT_SUCCESS",
            "EXIT_FAILURE",
        ],
    ),
    ("Storable", &["retrieve", "store"]),
    (
        "Test::More",
        &[
            "BAIL_OUT",
            "can_ok",
            "cmp_ok",
            "diag",
            "done_testing",
            "fail",
            "is",
            "is_deeply",
            "isa_ok",
            "isnt",
            "like",
            "new_ok",
            "note",
            "ok",
            "pass",
            "plan",
            "require_ok",
            "skip",
            "subtest",
            "unlike",
            "use_ok",
        ],
    ),
    ("Test::Simple", &["ok"]),
    ("Text::Wrap", &["fill", "wrap"]),
    ("Time::Local", &["timegm", "timelocal"]),
];

/// Perl's builtin functions (`perlfunc`), in `CORE::`: `print`, `push`,
/// `join`, `die`. A sub the file declares of the same name is called
/// instead only through `&name` or a prototype, so a declaration shadows.
const PERL_BUILTINS: &[&str] = &[
    "abs",
    "accept",
    "alarm",
    "atan2",
    "bind",
    "binmode",
    "bless",
    "caller",
    "chdir",
    "chmod",
    "chomp",
    "chop",
    "chown",
    "chr",
    "close",
    "closedir",
    "connect",
    "cos",
    "crypt",
    "defined",
    "delete",
    "die",
    "do",
    "each",
    "eof",
    "eval",
    "exec",
    "exists",
    "exit",
    "exp",
    "fcntl",
    "fileno",
    "flock",
    "fork",
    "format",
    "getc",
    "glob",
    "gmtime",
    "grep",
    "hex",
    "index",
    "int",
    "ioctl",
    "join",
    "keys",
    "kill",
    "lc",
    "lcfirst",
    "length",
    "link",
    "listen",
    "local",
    "localtime",
    "lock",
    "log",
    "lstat",
    "map",
    "mkdir",
    "oct",
    "open",
    "opendir",
    "ord",
    "pack",
    "pipe",
    "pop",
    "pos",
    "print",
    "printf",
    "prototype",
    "push",
    "quotemeta",
    "rand",
    "read",
    "readdir",
    "readline",
    "readlink",
    "recv",
    "ref",
    "rename",
    "require",
    "reset",
    "return",
    "reverse",
    "rewinddir",
    "rindex",
    "rmdir",
    "say",
    "scalar",
    "seek",
    "select",
    "send",
    "shift",
    "sin",
    "sleep",
    "socket",
    "sort",
    "splice",
    "split",
    "sprintf",
    "sqrt",
    "srand",
    "stat",
    "substr",
    "symlink",
    "syscall",
    "sysopen",
    "sysread",
    "system",
    "syswrite",
    "tell",
    "time",
    "truncate",
    "uc",
    "ucfirst",
    "umask",
    "undef",
    "unlink",
    "unpack",
    "unshift",
    "untie",
    "utime",
    "values",
    "vec",
    "wait",
    "waitpid",
    "wantarray",
    "warn",
    "write",
    "tie",
    "tied",
];

/// Whether `module` ships with perl.
pub(crate) fn is_perl_core_module(module: &str) -> bool {
    PERL_CORE_MODULES.contains(&module)
}

/// The names `use module;` (no import list) brings into the package.
pub(crate) fn perl_default_exports(module: &str) -> &'static [&'static str] {
    PERL_DEFAULT_EXPORTS
        .iter()
        .find(|(name, _)| *name == module)
        .map_or(&[], |(_, names)| names)
}

pub(crate) fn is_perl_builtin(name: &str) -> bool {
    PERL_BUILTINS.contains(&name)
}
