//! The R standard library: the base packages shipped with R, and the
//! common functions of those attached by default.

/// Packages shipped with R (priority `base`): `library(stats)` and
/// `stats::median` name the standard library, `library(dplyr)` does not.
const R_BASE_PACKAGES: &[&str] = &[
    "base",
    "compiler",
    "datasets",
    "grDevices",
    "graphics",
    "grid",
    "methods",
    "parallel",
    "splines",
    "stats",
    "stats4",
    "tcltk",
    "tools",
    "utils",
];

/// Common functions of `base`, callable bare in every R session.
const R_BASE_FUNCTIONS: &[&str] = &[
    "Filter",
    "Map",
    "Negate",
    "Recall",
    "Reduce",
    "Sys.Date",
    "Sys.getenv",
    "Sys.setenv",
    "Sys.sleep",
    "Sys.time",
    "abs",
    "all",
    "any",
    "anyNA",
    "append",
    "apply",
    "array",
    "as.character",
    "as.Date",
    "as.integer",
    "as.list",
    "as.logical",
    "as.numeric",
    "as.vector",
    "attr",
    "attributes",
    "basename",
    "c",
    "cat",
    "cbind",
    "ceiling",
    "character",
    "class",
    "colnames",
    "cumsum",
    "diff",
    "dim",
    "dirname",
    "do.call",
    "environment",
    "eval",
    "exists",
    "exp",
    "factor",
    "file.exists",
    "file.path",
    "floor",
    "format",
    "get",
    "grepl",
    "gsub",
    "identical",
    "identity",
    "ifelse",
    "inherits",
    "integer",
    "invisible",
    "is.character",
    "is.function",
    "is.list",
    "is.na",
    "is.null",
    "is.numeric",
    "lapply",
    "length",
    "levels",
    "list",
    "list.files",
    "log",
    "logical",
    "mapply",
    "match",
    "match.arg",
    "max",
    "mean",
    "message",
    "min",
    "missing",
    "names",
    "nchar",
    "ncol",
    "new.env",
    "nrow",
    "numeric",
    "on.exit",
    "order",
    "paste",
    "paste0",
    "print",
    "range",
    "rbind",
    "readLines",
    "readRDS",
    "regmatches",
    "regexpr",
    "rep",
    "rep_len",
    "return",
    "rev",
    "rm",
    "round",
    "rownames",
    "sapply",
    "saveRDS",
    "seq",
    "seq_along",
    "seq_len",
    "setdiff",
    "signif",
    "sort",
    "split",
    "sprintf",
    "sqrt",
    "stop",
    "stopifnot",
    "strsplit",
    "structure",
    "sub",
    "substr",
    "substring",
    "sum",
    "suppressWarnings",
    "switch",
    "sys.call",
    "system",
    "system.file",
    "table",
    "tolower",
    "toupper",
    "trimws",
    "try",
    "tryCatch",
    "typeof",
    "union",
    "unique",
    "unlist",
    "vapply",
    "vector",
    "warning",
    "which",
    "which.max",
    "which.min",
    "with",
    "writeLines",
    "data.frame",
    "matrix",
    "nlevels",
    "is.element",
    "emptyenv",
    "globalenv",
    "local",
    "t",
    "unsplit",
    "mode",
    "prod",
    "xor",
    "isTRUE",
    "isFALSE",
];

/// Common functions of `stats`, attached by default.
const R_STATS_FUNCTIONS: &[&str] = &[
    "aggregate",
    "anova",
    "coef",
    "cor",
    "cov",
    "dbinom",
    "density",
    "dnorm",
    "fitted",
    "glm",
    "lm",
    "median",
    "model.matrix",
    "na.omit",
    "optim",
    "pbinom",
    "pnorm",
    "predict",
    "qnorm",
    "quantile",
    "rbinom",
    "residuals",
    "rnorm",
    "rpois",
    "runif",
    "sd",
    "setNames",
    "t.test",
    "var",
    "weighted.mean",
    "xtabs",
];

/// Common functions of `utils`, attached by default.
const R_UTILS_FUNCTIONS: &[&str] = &[
    "combn",
    "capture.output",
    "data",
    "head",
    "install.packages",
    "modifyList",
    "packageVersion",
    "read.csv",
    "read.delim",
    "read.table",
    "sessionInfo",
    "str",
    "tail",
    "write.csv",
    "write.table",
];

/// Common functions of `graphics` / `grDevices`, attached by default.
const R_GRAPHICS_FUNCTIONS: &[&str] = &[
    "abline", "barplot", "boxplot", "hist", "legend", "lines", "par", "plot", "points", "text",
];
const R_GRDEVICES_FUNCTIONS: &[&str] = &["dev.off", "pdf", "png", "rgb"];

/// Whether `package` is shipped with R.
pub(crate) fn is_r_base_package(package: &str) -> bool {
    R_BASE_PACKAGES.contains(&package)
}

/// The default-attached base package a bare function name belongs to
/// (`paste` → `base`, `median` → `stats`, `head` → `utils`).
pub(crate) fn r_default_package(name: &str) -> Option<&'static str> {
    [
        ("base", R_BASE_FUNCTIONS),
        ("stats", R_STATS_FUNCTIONS),
        ("utils", R_UTILS_FUNCTIONS),
        ("graphics", R_GRAPHICS_FUNCTIONS),
        ("grDevices", R_GRDEVICES_FUNCTIONS),
    ]
    .into_iter()
    .find(|(_, names)| names.contains(&name))
    .map(|(package, _)| package)
}
