//! The Ruby standard library: the core classes every program has, the
//! `Kernel` methods called without a receiver, and the libraries (and
//! default gems) shipped with Ruby that a `require` loads.

/// Libraries shipped with Ruby, by the name `require` loads them with (its
/// first path segment: `net/http` is `net`, `digest/md5` is `digest`).
const RUBY_STDLIB_LIBRARIES: &[&str] = &[
    "English",
    "abbrev",
    "base64",
    "benchmark",
    "bigdecimal",
    "cgi",
    "coverage",
    "csv",
    "date",
    "delegate",
    "digest",
    "drb",
    "erb",
    "etc",
    "expect",
    "fcntl",
    "fiber",
    "fiddle",
    "fileutils",
    "find",
    "forwardable",
    "getoptlong",
    "io",
    "ipaddr",
    "irb",
    "json",
    "logger",
    "matrix",
    "monitor",
    "mutex_m",
    "net",
    "objspace",
    "observer",
    "open-uri",
    "open3",
    "openssl",
    "optparse",
    "ostruct",
    "pathname",
    "pp",
    "prettyprint",
    "prime",
    "pstore",
    "psych",
    "racc",
    "rdoc",
    "readline",
    "reline",
    "resolv",
    "rinda",
    "ripper",
    "securerandom",
    "set",
    "shellwords",
    "singleton",
    "socket",
    "stringio",
    "strscan",
    "syslog",
    "tempfile",
    "time",
    "timeout",
    "tmpdir",
    "tsort",
    "un",
    "uri",
    "weakref",
    "yaml",
    "zlib",
];

/// Constants the standard libraries define, with the library that does:
/// `JSON.parse` is `json`'s, `Net::HTTP.get` is `net/http`'s.
const RUBY_STDLIB_CONSTANTS: &[(&str, &str)] = &[
    ("Abbrev", "abbrev"),
    ("Base64", "base64"),
    ("Benchmark", "benchmark"),
    ("BigDecimal", "bigdecimal"),
    ("CGI", "cgi"),
    ("CSV", "csv"),
    ("Coverage", "coverage"),
    ("DRb", "drb"),
    ("Date", "date"),
    ("DateTime", "date"),
    ("DelegateClass", "delegate"),
    ("Digest", "digest"),
    ("ERB", "erb"),
    ("Etc", "etc"),
    ("Fiddle", "fiddle"),
    ("FileUtils", "fileutils"),
    ("Find", "find"),
    ("Forwardable", "forwardable"),
    ("GetoptLong", "getoptlong"),
    ("IPAddr", "ipaddr"),
    ("JSON", "json"),
    ("Logger", "logger"),
    ("Matrix", "matrix"),
    ("Monitor", "monitor"),
    ("Net::FTP", "net/ftp"),
    ("Net::HTTP", "net/http"),
    ("Net::IMAP", "net/imap"),
    ("Net::SMTP", "net/smtp"),
    ("Observable", "observer"),
    ("Open3", "open3"),
    ("OpenSSL", "openssl"),
    ("OpenStruct", "ostruct"),
    ("OpenURI", "open-uri"),
    ("OptionParser", "optparse"),
    ("PP", "pp"),
    ("PStore", "pstore"),
    ("Pathname", "pathname"),
    ("Prime", "prime"),
    ("Psych", "psych"),
    ("Readline", "readline"),
    ("Resolv", "resolv"),
    ("Ripper", "ripper"),
    ("SecureRandom", "securerandom"),
    ("Set", "set"),
    ("Shellwords", "shellwords"),
    ("SimpleDelegator", "delegate"),
    ("Singleton", "singleton"),
    ("SortedSet", "set"),
    ("StringIO", "stringio"),
    ("StringScanner", "strscan"),
    ("Syslog", "syslog"),
    ("TCPServer", "socket"),
    ("TCPSocket", "socket"),
    ("TSort", "tsort"),
    ("Tempfile", "tempfile"),
    ("Timeout", "timeout"),
    ("UDPSocket", "socket"),
    ("UNIXSocket", "socket"),
    ("URI", "uri"),
    ("WeakRef", "weakref"),
    ("YAML", "yaml"),
    ("Zlib", "zlib"),
];

/// Classes and modules of Ruby's core, defined before any `require`: a
/// call on one (`File.read`, `Struct.new`) is the core's.
const RUBY_CORE_CONSTANTS: &[&str] = &[
    "ARGF",
    "ARGV",
    "Array",
    "BasicObject",
    "Binding",
    "Class",
    "Comparable",
    "Complex",
    "Data",
    "Dir",
    "ENV",
    "Encoding",
    "Enumerable",
    "Enumerator",
    "Errno",
    "FalseClass",
    "Fiber",
    "File",
    "FileTest",
    "Float",
    "GC",
    "Hash",
    "IO",
    "Integer",
    "Kernel",
    "Marshal",
    "MatchData",
    "Math",
    "Method",
    "Module",
    "Mutex",
    "NilClass",
    "Numeric",
    "Object",
    "ObjectSpace",
    "Proc",
    "Process",
    "Queue",
    "Ractor",
    "Random",
    "Range",
    "Rational",
    "Regexp",
    "Signal",
    "SizedQueue",
    "String",
    "Struct",
    "Symbol",
    "Thread",
    "Time",
    "TracePoint",
    "TrueClass",
    "UnboundMethod",
    "Warning",
    // Exceptions.
    "ArgumentError",
    "EOFError",
    "EncodingError",
    "Exception",
    "FiberError",
    "FloatDomainError",
    "FrozenError",
    "IOError",
    "IndexError",
    "Interrupt",
    "KeyError",
    "LoadError",
    "LocalJumpError",
    "NameError",
    "NoMatchingPatternError",
    "NoMemoryError",
    "NoMethodError",
    "NotImplementedError",
    "RangeError",
    "RegexpError",
    "RuntimeError",
    "ScriptError",
    "SecurityError",
    "SignalException",
    "StandardError",
    "StopIteration",
    "SyntaxError",
    "SystemCallError",
    "SystemExit",
    "SystemStackError",
    "ThreadError",
    "TypeError",
    "UncaughtThrowError",
    "ZeroDivisionError",
];

/// `Kernel` methods, called without a receiver from anywhere (`puts`,
/// `raise`, `format`).
const RUBY_KERNEL_METHODS: &[&str] = &[
    "Array",
    "Float",
    "Hash",
    "Integer",
    "Rational",
    "String",
    "__dir__",
    "__method__",
    "abort",
    "at_exit",
    "binding",
    "block_given?",
    "caller",
    "catch",
    "exit",
    "exit!",
    "fail",
    "fork",
    "format",
    "gets",
    "lambda",
    "loop",
    "open",
    "p",
    "pp",
    "print",
    "printf",
    "proc",
    "putc",
    "puts",
    "raise",
    "rand",
    "readline",
    "readlines",
    "sleep",
    "spawn",
    "sprintf",
    "srand",
    "system",
    "throw",
    "trap",
    "warn",
];

/// Whether `require name` loads a library shipped with Ruby.
pub(crate) fn is_ruby_stdlib_library(name: &str) -> bool {
    RUBY_STDLIB_LIBRARIES.contains(&ruby_library_root(name))
}

/// The first path segment of a required library (`net/http` → `net`), by
/// which a `require` and the constants it defines are matched.
pub(crate) fn ruby_library_root(name: &str) -> &str {
    name.split('/').next().unwrap_or(name)
}

/// The library that defines a standard-library constant, looked up by its
/// full path and then by its outermost module (`Digest::SHA256` is
/// `digest`'s).
pub(crate) fn ruby_stdlib_constant_library(path: &str) -> Option<&'static str> {
    let root = path.split("::").next().unwrap_or(path);
    [path, root].into_iter().find_map(|name| {
        RUBY_STDLIB_CONSTANTS
            .iter()
            .find(|(constant, _)| *constant == name)
            .map(|(_, library)| *library)
    })
}

pub(crate) fn is_ruby_core_constant(name: &str) -> bool {
    RUBY_CORE_CONSTANTS.contains(&name)
}

pub(crate) fn is_ruby_kernel_method(name: &str) -> bool {
    RUBY_KERNEL_METHODS.contains(&name)
}
