/* eslint-disable */
/**
 * Demo API
 * NOTE: This class is auto generated by OpenAPI Generator.
 */

export interface HealthResponse {
  status: string;
}

export async function getHealth(): Promise<HealthResponse> {
  return { status: "ok" };
}
