//! Where a repository's graph lives, created on demand for a build.

use std::path::{Path, PathBuf};

const INNER_GITIGNORE: &str = "# Auto-generated by dagayn \u{2014} do not commit database files.\n\
# The graph.db contains absolute paths and code structure metadata.\n\
*\n";

#[derive(Debug, thiserror::Error)]
pub enum DataDirError {
    #[error(
        "CRG_DATA_DIR is not supported by this build of dagayn yet; \
         unset it or use the Python CLI"
    )]
    SharedDataDirUnsupported,
    #[error("cannot create {path}: {source}")]
    Create {
        path: PathBuf,
        source: std::io::Error,
    },
}

/// `<repo_root>/.dagayn/graph.db`, creating the directory and its `.gitignore`.
///
/// Matches `dagayn.paths.get_db_path` for the default layout. The shared
/// `CRG_DATA_DIR` layout and the legacy `.dagayn.db` migration are not ported.
pub fn db_path_for_build(repo_root: &Path) -> Result<PathBuf, DataDirError> {
    if std::env::var_os("CRG_DATA_DIR").is_some_and(|value| !value.is_empty()) {
        return Err(DataDirError::SharedDataDirUnsupported);
    }
    let data_dir = repo_root.join(".dagayn");
    std::fs::create_dir_all(&data_dir).map_err(|source| DataDirError::Create {
        path: data_dir.clone(),
        source,
    })?;
    let gitignore = data_dir.join(".gitignore");
    if !gitignore.exists() {
        // Best effort, as in Python: the graph is usable without it.
        let _ = std::fs::write(&gitignore, INNER_GITIGNORE);
    }
    Ok(data_dir.join("graph.db"))
}

/// The other repository a graph says it describes, if any:
/// `_assert_graph_matches_repo` in Python. A recorded root that no longer
/// exists counts as this repository (a moved or renamed checkout); only an
/// existing, different directory is a mismatch.
pub fn graph_repo_mismatch(store: &dagayn_graph::GraphStore, repo_root: &Path) -> Option<PathBuf> {
    let recorded = PathBuf::from(store.get_metadata("repo_root").ok().flatten()?);
    if recorded.as_os_str().is_empty() || recorded == repo_root {
        return None;
    }
    match (recorded.canonicalize(), repo_root.canonicalize()) {
        (Ok(left), Ok(right)) if left == right => None,
        (Err(_), _) => None,
        _ => Some(recorded),
    }
}

/// The message Python's `RepoRootMismatchError` carries.
pub fn graph_repo_mismatch_message(db_path: &Path, recorded: &Path, repo_root: &Path) -> String {
    format!(
        "the graph at {} describes {}, not {}, so its results would belong to a different \
         repository. Pass repo_root explicitly (MCP tools), set CRG_REPO_ROOT, or give the \
         MCP server entry a cwd/--repo for this project; editors that launch the server \
         without one resolve the repository from an ambient working directory.",
        db_path.display(),
        recorded.display(),
        repo_root.display()
    )
}
