//! Where a repository's graph lives, created on demand for a build.

use std::path::{Path, PathBuf};

const INNER_GITIGNORE: &str = "# Auto-generated by dagayn \u{2014} do not commit database files.\n\
# The graph.db contains absolute paths and code structure metadata.\n\
*\n";

#[derive(Debug, thiserror::Error)]
pub enum DataDirError {
    #[error(
        "CRG_DATA_DIR is not supported by this build of dagayn yet; \
         unset it or use the Python CLI"
    )]
    SharedDataDirUnsupported,
    #[error("cannot create {path}: {source}")]
    Create {
        path: PathBuf,
        source: std::io::Error,
    },
}

/// `<repo_root>/.dagayn/graph.db`, creating the directory and its `.gitignore`.
///
/// Matches `dagayn.paths.get_db_path` for the default layout. The shared
/// `CRG_DATA_DIR` layout and the legacy `.dagayn.db` migration are not ported.
pub fn db_path_for_build(repo_root: &Path) -> Result<PathBuf, DataDirError> {
    if std::env::var_os("CRG_DATA_DIR").is_some_and(|value| !value.is_empty()) {
        return Err(DataDirError::SharedDataDirUnsupported);
    }
    let data_dir = repo_root.join(".dagayn");
    std::fs::create_dir_all(&data_dir).map_err(|source| DataDirError::Create {
        path: data_dir.clone(),
        source,
    })?;
    let gitignore = data_dir.join(".gitignore");
    if !gitignore.exists() {
        // Best effort, as in Python: the graph is usable without it.
        let _ = std::fs::write(&gitignore, INNER_GITIGNORE);
    }
    Ok(data_dir.join("graph.db"))
}
