from __future__ import annotations

from collections.abc import Callable
from os import PathLike
from pathlib import Path
from typing import Any

class GraphStore:
    """Native graph store.

    Implements the same method surface as :class:`dagayn.graph.GraphStore`, so
    tools can hold either without probing for `_conn`. `__getattr__` keeps the
    stub open rather than restating ~90 signatures; the parity contract itself
    is asserted by ``tests/test_rust_graph_store_parity.py``.
    """

    _pinned: bool
    _leases: int
    db_path: Path

    def __init__(self, db_path: str | PathLike[str]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def filter_incremental_candidates(
    repo_root: str | PathLike[str],
    candidates: list[str],
    ignore_patterns: list[str],
) -> tuple[list[str], list[str]]: ...
def filter_parseable_files(
    repo_root: str | PathLike[str],
    candidates: list[str],
    ignore_patterns: list[str],
) -> list[str]: ...
def filter_ignored_paths(candidates: list[str], ignore_patterns: list[str]) -> list[str]: ...
def collect_parseable_files(
    repo_root: str | PathLike[str],
    recurse_submodules: bool | None = None,
) -> list[str]: ...
def parse_rust_owned_files_compact_json(
    repo_root: str | PathLike[str],
    file_paths: list[str],
) -> str: ...
def parse_rust_owned_file_compact_json(file_path: str, source: bytes) -> str: ...
def parse_markdown_compact_json(file_path: str, source: bytes) -> str: ...
def parse_terraform_compact_json(file_path: str, source: bytes) -> str: ...
def parse_rust_compact_json(file_path: str, source: bytes) -> str: ...
def parse_python_compact_json(file_path: str, source: bytes) -> str: ...
def extractor_versions() -> list[tuple[str, int, list[str]]]: ...
def discover_manifest_bridges_json(
    repo_root: str | PathLike[str],
    scope: list[str] | None = None,
) -> str: ...
def resolve_manifest_path(base_dir: str, declared: str) -> str | None: ...
def run_cli(argv: list[str]) -> int | None: ...
def serve_mcp(
    surface_json: str,
    allowed_tools: list[str] | None,
    version: str,
    boot: Callable[[int, int], None],
    pinned_repo: str | None = None,
    package_root: str | None = None,
    local_embedding: str | None = None,
    embedding_provider: str | None = None,
    embedding_model: str | None = None,
    runtime: str | None = None,
) -> None: ...
def embedding_search(
    db_path: str | PathLike[str],
    provider: str,
    query_vec: list[float],
    limit: int,
) -> list[tuple[str, float]]: ...
def embedding_search_prewarm(
    db_path: str | PathLike[str],
    provider: str,
) -> int: ...

class HintSession:
    """A handle on the process's ``dagayn.hints`` session, shared with Rust."""

    inferred_intent: str | None
    def __init__(self) -> None: ...
    @property
    def tools_called(self) -> list[str]: ...
    @property
    def nodes_queried(self) -> set[str]: ...
    @property
    def files_touched(self) -> set[str]: ...
    @property
    def last_tool_time(self) -> float: ...
    def record_tool_call(self, tool_name: str) -> None: ...
    def record_nodes(self, node_ids: list[str]) -> None: ...
    def record_files(self, files: list[str]) -> None: ...
    def generate_hints(
        self, tool_name: str, result_json: str, exposed: set[str] | None = None
    ) -> str: ...

def reset_hint_session() -> None: ...
def pending_refactor_set(refactor_id: str, payload_json: str) -> None: ...
def pending_refactor_get(refactor_id: str) -> str | None: ...
def pending_refactor_remove(refactor_id: str) -> str | None: ...
def pending_refactor_keys() -> list[str]: ...
def pending_refactor_clear() -> None: ...
