"""Where a repository's graph data lives.

Kept apart from :mod:`dagayn.incremental_files` so that import-light callers —
agent hooks, :mod:`dagayn.worktree` — can resolve a graph path without pulling
in the parser. :mod:`dagayn.incremental_files` re-exports these names, so
``from dagayn.incremental import get_db_path`` keeps working.
"""

from __future__ import annotations

import hashlib
import logging
import os
import re
import sqlite3
from pathlib import Path

logger = logging.getLogger(__name__)


def repo_slug(repo_root: Path) -> str:
    """Return a stable, filesystem-safe directory name for *repo_root*.

    The readable part is the directory name; the suffix is a digest of the
    absolute path, so two checkouts of the same project — or two worktrees —
    never collide.
    """
    resolved = Path(repo_root).expanduser().resolve()
    digest = hashlib.sha256(str(resolved).encode("utf-8")).hexdigest()[:12]
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", resolved.name).strip("-") or "repo"
    return f"{name}-{digest}"


def get_data_dir(repo_root: Path) -> Path:
    """Return the directory where this project's graph data lives.

    By default, ``<repo_root>/.dagayn``. If the ``CRG_DATA_DIR`` environment
    variable is set, graph data goes to a per-repository subdirectory of it,
    ``<CRG_DATA_DIR>/<name>-<path digest>`` — letting you keep graphs outside
    the working tree (useful for ephemeral workspaces, Docker volumes, or
    shared caches). See: #155

    The subdirectory matters: ``CRG_DATA_DIR`` used to be honored verbatim, so
    every repository and worktree that saw the variable shared one
    ``graph.db``. Exporting it from a shell profile silently mixed several
    projects' nodes into a single graph, with ``repo_root`` metadata belonging
    to whichever one last wrote.

    A pre-existing ``<CRG_DATA_DIR>/graph.db`` is migrated into the
    subdirectory when its ``repo_root`` metadata names *this* repository, so a
    single-repository setup keeps its graph.

    The directory is created if it does not already exist; an inner
    ``.gitignore`` (with ``*``) is written so any accidentally-nested
    files never get committed. Both are idempotent.
    """
    env_override = os.environ.get("CRG_DATA_DIR", "").strip()
    if env_override:
        shared_dir = Path(env_override).expanduser().resolve()
        data_dir = shared_dir / repo_slug(repo_root)
        data_dir.mkdir(parents=True, exist_ok=True)
        _migrate_shared_data_dir(shared_dir, data_dir, repo_root)
    else:
        data_dir = repo_root / ".dagayn"

    data_dir.mkdir(parents=True, exist_ok=True)

    inner_gitignore = data_dir / ".gitignore"
    if not inner_gitignore.exists():
        try:
            # `encoding="utf-8"` is REQUIRED — the em-dash in the header is
            # U+2014 which falls outside cp1252.  On Windows, calling
            # write_text without an encoding silently uses the system default
            # codepage, producing a file that subsequently fails to decode as
            # UTF-8 (see issue #239).
            inner_gitignore.write_text(
                "# Auto-generated by dagayn — do not commit database files.\n"
                "# The graph.db contains absolute paths and code structure metadata.\n"
                "*\n",
                encoding="utf-8",
            )
        except OSError:
            # Data dir might be read-only (rare); that's OK, it's a best-effort guard.
            pass

    return data_dir


def _shared_graph_belongs_to(db_path: Path, repo_root: Path) -> bool:
    """Return True when *db_path* records *repo_root* as its repository."""
    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    except sqlite3.Error:
        return False
    try:
        row = conn.execute("SELECT value FROM metadata WHERE key = 'repo_root'").fetchone()
    except sqlite3.Error:
        return False
    finally:
        conn.close()
    if not row or not row[0]:
        return False
    try:
        return Path(str(row[0])).resolve() == Path(repo_root).expanduser().resolve()
    except (OSError, RuntimeError):
        return False


def _migrate_shared_data_dir(shared_dir: Path, data_dir: Path, repo_root: Path) -> None:
    """Move a pre-subdirectory ``CRG_DATA_DIR`` graph into *data_dir*.

    Only when the graph says it describes *repo_root*: a graph belonging to
    another repository must stay where it is rather than be claimed by whoever
    runs next. Side-files are dropped — the graph is checkpointed on close, and
    a stale WAL cannot be matched to a moved database with confidence.
    """
    legacy_db = shared_dir / "graph.db"
    target_db = data_dir / "graph.db"
    if target_db.exists() or not legacy_db.exists():
        return
    if not _shared_graph_belongs_to(legacy_db, repo_root):
        return
    try:
        legacy_db.rename(target_db)
    except OSError as exc:
        logger.warning("Could not move %s into %s: %s", legacy_db, data_dir, exc)
        return
    for suffix in ("-wal", "-shm", "-journal"):
        side = shared_dir / f"graph.db{suffix}"
        if side.exists():
            try:
                side.unlink()
            except OSError:  # nosec B110 — best-effort cleanup
                pass
    logger.info("Moved shared CRG_DATA_DIR graph into %s", data_dir)


def get_db_path(repo_root: Path) -> Path:
    """Determine the database path for a repository.

    Respects ``CRG_DATA_DIR`` (see :func:`get_data_dir`). Migrates a
    legacy top-level ``.dagayn.db`` file into the new
    directory when it exists (WAL/SHM side-files are discarded).
    """
    crg_dir = get_data_dir(repo_root)
    new_db = crg_dir / "graph.db"

    # Migrate legacy database if present (only meaningful when the
    # legacy file sits at the repo root — if CRG_DATA_DIR is set we
    # skip the migration because there's no relationship between the
    # legacy location and the new one).
    legacy_db = repo_root / ".dagayn.db"
    if legacy_db.exists() and not new_db.exists():
        legacy_db.rename(new_db)
    # Discard stale WAL/SHM side-files from the old location
    for suffix in ("-wal", "-shm", "-journal"):
        side = repo_root / f".dagayn.db{suffix}"
        if side.exists():
            side.unlink()

    return new_db
